<?php
namespace App\Model;
use EasySwoole\ORM\AbstractModel;

/**
 * Class BaseModel
 * Create With Automatic Generator
 */
class BaseOrmModel extends AbstractModel
{

//    function data(array $data, $setter = true)
//    {
//        return parent::data($data, $setter); // TODO: Change the autogenerated stub
//    }
//
//    function save()
//    {
//        return parent::save(); // TODO: Change the autogenerated stub
//    }


}